regex = [r"(?P<species_type>(mouse|human))\s+(?P<age_no_min>\d+)\s+(?P<age_time_unit_min>\w+)\s+(?P<age_no_max>\d+)\s+(?P<age_time_unit_max>\w+)\s+$",
r"(?P<species_type>(mouse|human))\s+(?P<age_no_min>\d+)\s+(?P<age_time_unit_min>\w+)\s+$",
r"(?P<species_type>(mouse|human))\s+(?P<age_no_min>\d+)\s+(?P<age_time_unit_min>\w+)\s+(?P<age_no_max>\d+)\s+(?P<age_time_unit_max>\w+)\s+(?P<tissue_type>(other))\s+(?P<tissue_type_define_other>(oviduct|uterus|macrophage (CL:0000235)|GFP-Tg lesions|peritoneal))\s+(?P<vivo_vitro>(in vivo|in vitro (cells)))\s+$",
r"(?P<species_type>(mouse|human))\s+(?P<age_no_min>\d+)\s+(?P<age_time_unit_min>\w+)\s+(?P<age_no_max>\d+)\s+(?P<age_time_unit_max>\w+)\s+(?P<tissue_type>ovary)\s+(?P<vivo_vitro>(in vivo|in vitro (cells)))\s+$",
r"(?P<species_type>(mouse|human))\s+(?P<age_no_min>\d+)\s+(?P<age_time_unit_min>\w+)\s+(?P<age_no_max>\d+)\s+(?P<age_time_unit_max>\w+)\s+(?P<tissue_type>(other|endometrium))\s+(?P<tissue_type_define_other>(oviduct|uterus|macrophage (CL:0000235)|GFP-Tg lesions|peritoneal))\s+(?P<vivo_vitro>(in vivo|in vitro (cells)))\s+$",
r"(?P<species_type>(human|mouse))\s+(?P<age_no_min>\d+)\s+(?P<age_time_unit_min>\w+)\s+(?P<age_no_max>\d+)\s+(?P<age_time_unit_max>\w+)\s+(?P<tissue_type>(other|endometrium))\s+(?P<tissue_type_define_other>(oviduct|uterus|macrophage (CL:0000235)|GFP-Tg lesions|peritoneal))\s+(?P<vivo_vitro>(in vivo|in vitro (cells)))\s+$",
r"(?P<species_type>(human|mouse))\s+(?P<age_no_min>\d+)\s+(?P<age_time_unit_min>\w+)\s+(?P<age_no_max>\d+)\s+(?P<age_time_unit_max>\w+)\s+(?P<tissue_type>(other|ovary|endometrium))\s+(?P<vivo_vitro>(in vivo|in vitro (cells)))\s+$",r"(?P<species_type>(human|mouse))\s+(?P<age_no_min>\d+)\s+(?P<age_time_unit_min>\w+)\s+(?P<tissue_type>other)\s+(?P<tissue_type_define_other>(oviduct|uterus|macrophage (CL:0000235)|GFP-Tg lesions|peritoneal))\s+(?P<vivo_vitro>(in vivo|in vitro (cells)))\s+$",r"(?P<species_type>(human|mouse))\s+(?P<strain>(CBA x DBA|CBA|CBA x BALB/c))\s+(?P<age_no_min>\d+)\s+(?P<age_time_unit_min>\w+)\s+(?P<tissue_type>other)\s+(?P<tissue_type_define_other>\w+\s+\(\w+:\d+\))\s+(?P<vivo_vitro>(\w+\s+\w+|\w+\s+\w+\s+\(\w+\)))\s+$",
r"(?P<species_type>(human|mouse))\s+(?P<strain>(CBA x DBA|CBA|CBA x BALB/c))\s+(?P<age_no_min>\d+)\s+(?P<age_time_unit_min>\w+)\s+(?P<tissue_type>other)\s+(?P<tissue_type_define_other>macrophage (CL:0000235))\s+(?P<vivo_vitro>(in vivo|in vitro (cells)))\s+$",
r"(?P<species_type>(human|mouse))\s+(?P<strain>(CBA x DBA|CBA|CBA x BALB/c))\s+(?P<age_no_min>\d+)\s+(?P<age_time_unit_min>\w+)\s+(?P<tissue_type>(other|ovary|endometrium))\s+(?P<tissue_type_define_other>(oviduct|uterus|'macrophage (CL:0000235)'|GFP-Tg lesions|peritoneal))\s+(?P<vivo_vitro>(\w+\s+\w+|\w+\s+\w+\s+\(\w+\)))\s+$",
r"(?P<species_type>(human|mouse))\s+(?P<ethnicity>\w+\s+\w+)\s+(?P<number_of_subjects>\d+)\s+(?P<age_no_min>\d+)\s+(?P<age_time_unit_min>\w+)\s+(?P<age_no_max>\d+)\s+(?P<age_time_unit_max>\w+)\s+(?P<tissue_type>\w+)\s+(?P<tissue_type_define_other>(\w+|\w+\-\w+\s+\w+))\s+(?P<endometriosis_attributes>\w+\s+\w+)\s+(?P<endometriosis_stage>\(\w+\)\s+\w+\s+\w+\s+\(\w+\))\s+$",
r"(?P<species_type>(human|mouse))\s+(?P<ethnicity>\w+\s+\w+)\s+(?P<age_no_min>\d+)\s+(?P<age_time_unit_min>\w+)\s+(?P<age_no_max>\d+)\s+(?P<age_time_unit_max>\w+)\s+(?P<tissue_type>\w+)\s+(?P<tissue_type_define_other>(\w+|\w+\-\w+\s+\w+))\s+(?P<endometriosis_attributes>\w+\s+\w+)\s+(?P<endometriosis_stage>\(\w+\)\s+\w+\s+\w+\s+\(\w+\))\s+$",
r"(?P<species_type>(mouse|human))\s+(?P<age_no_min>\d+)\s+(?P<age_time_unit_min>\w+)\s+(?P<age_no_max>\d+)\s+(?P<age_time_unit_max>\w+)\s+(?P<tissue_type>\w+)\s+(?P<tissue_type_define_other>(\w+|\w+\-\w+\s+\w+))\s+$",
r"(?P<species_type>human)\s+(?P<age_no_min>\d+)\s+(?P<age_time_unit_min>\w+)\s+(?P<age_no_max>\d+)\s+(?P<age_time_unit_max>\w+)\s+(?P<age_mean>\d+\.\d+)\s+(?P<BMI>\d+\.\d+)\s+(?P<tissue_type>ovary)\s+(?P<vivo_vitro>\w+\s+\w+)\s+(?P<ovary_specifics>\w+\s+\w+)\s+(?P<pathological_state>(\w+\-\w+\s+\w+|\w+))\s+(?P<diagnosis>([A-Z]+|\w+\s+\w+\s+\w+))\s+(?P<pcos_attributes>(\w+\s\w+\s\w+|\w+\s\w+))\s+$",
r"(?P<species_type>human)\s+(?P<age_no_min>\d+)\s+(?P<age_time_unit_min>\w+)\s+(?P<age_no_max>\d+)\s+(?P<age_time_unit_max>\w+)\s+(?P<age_mean>\d+\.\d+)\s+(?P<BMI>\d+\.\d+)\s+(?P<tissue_type>ovary)\s+(?P<vivo_vitro>\w+\s+\w+)\s+(?P<ovary_specifics>\w+\s+\w+)\s+(?P<pathological_state>(\w+\-\w+\s+\w+|\w+))\s+(?P<diagnosis>([A-Z]+|\w+\s+\w+\s+\w+))\s+$"]



